Fix querying IPs from existing servers
e-minguez/kubernetes-the-hard-way-osp pull request #9
Opened 2022-05-30 09:45 UTC by Syphdias

The output from `openstack server show` command is different when using
`-f value`. This means that the assumptions for the awk commands to
extract the IPs are off.

To fix this I used json formatting instead and `jq` to extract the IPs
more easily. In one case I decided to hard code the internal DNS IP
since it was set earlier to be something specific, so no need to query
it.

For the adjustments in /etc/hosts and keyscanning I added a filter for
the DOMAIN in case there are other servers in the project.

2022-05-30 15:28 UTC, e-minguez requested changes
Minor comment about avoid hardcoding the IP👍
Otherwise LGTM!

2022-06-03 16:26 UTC, Syphdias commented on docs/03-compute-resources.md
> +openstack subnet set --dns-nameserver 10.240.0.100 kubernetes
Resolved

2022-06-03 16:28 UTC, Syphdias commented
I added a section for CLI perquisites, mainly for `jq` but I also listed `ssh` and `scp`. Is there anything I should add?

2022-06-03 20:35 UTC, e-minguez commented
That's awesome, thanks! 😃

2022-06-03 20:35 UTC, e-minguez approved these changes

2022-06-03 20:35 UTC, merged